---
title: "Syllabus"
book_filename: "current-issues-capstone"
output:
  word_document:
    toc: true
  pdf_document:
    toc: false
  html_document:
    toc: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<p align="center">**San Jos&eacute; State University**</p>

<p align="center">**Department of Psychology**</p>

<p align="center">**PSYC 190: Current Issues Capstone: Human-Systems Integration in Cyber, Health, and Transport**</p>

<p align="center">**Section 83, Spring 2025**</p>

<p align="center">Last updated: `r format(Sys.time(), '%B %d, %Y')`</p>

<p align="center">**This version may be out of date. Find the [latest version here](https://vectrlab.github.io/capstone-syllabus/index.html)**</p>


# Instructor Contact Information
Instructor:	      David Schuster, Ph.D.

Office Location:	DMH 321

Telephone:	      408-924-5659

Email:	          david.schuster@sjsu.edu

Office Hours:	    Tuesdays and Thursdays 11:30am-12:30pm in person and on [Zoom meeting](https://sjsu.zoom.us/j/86362443375?pwd=ZCsvMzdFWldBUTV3WGZ4a1lwaUtGdz09); also available by appointment

# Course Information
Classroom:	      Online; this is an asynchronous course

Class Days/Time:	Online

Prerequisite:	PSYC 100W

Co/prerequisite:	PSYC 118 or PSYC 120

This is a no-cost materials course.

# Welcome!

My name is Dr. David Schuster, and you are welcome to call me 'Dave,' 'David,' or 'Dr. Schuster.' My preferred pronouns are he/him/his. I have been teaching since 2008 and a professor at SJSU since 2013. I earned my Ph.D. in psychology from the University of Central Florida. I am looking forward to being your instructor as we explore how psychological research can increase the safety and effectiveness of human-machine systems.

# Course Description
In this capstone course, we will investigate how psychological research can be applied to large-scale systems of people and technology. We will focus on three important domains, cybersecurity, healthcare, and transportation. We will discover how they are similar and different from an applied research perspective. We will consider how different psychological perspectives inform solutions to societal problems. Through the process, you will practice and develop your skills as a researcher by developing a proposal for a new study. A major part of this course will involve reading, considering, and discussing scientific literature available to us from the King Library.

The catalog description of this course is an: Integrative survey of current viewpoints and issues in psychology, how they developed and likely future directions of psychology. 

This course builds on themes introduced in PSYC 173 (Human Factors) but does not require it.


## Course Format

This is an asynchronous online course. That means that you will complete each week's material at your own pace.

# Learning Outcomes {#learningoutcomes}

## Course Learning Outcomes {#clos}

The major goal of this course is to show students how applied psychological research informs practice in domains of human-technology interaction.

Upon successful completion of this course, students will be able to:

-	CLO1 - Describe human-systems integration, appropriately use its fundamental terminology, and describe its importance in the effectiveness of cybersecurity, transportation, and healthcare systems

-	CLO2 - Apply research, principles, and methods of human factors to human-machine system design, system evaluation, and training in cybersecurity, transportation, and healthcare systems.

-	CLO3 - Describe how cognitive psychology, perception, industrial/organizational psychology, and the science of learning inform human-systems integration.

-	CLO4 – Develop a novel research study and describe its hypotheses, variables, design, expected results, and research question.

The learning outcomes will be assessed via written assignments and presentation content. 

## Program Learning Outcomes {#plos}
Upon successful completion of the requirements for a major in psychology, students will be able to:

-	PLO1 – Knowledge Base of Psychology – identify, describe, and communicate the major concepts, theoretical perspectives, empirical findings, and historical trends in psychology

-	PLO2 – Research Methods in Psychology – design, implement, and communicate basic research methods in psychology, including research design, data analysis, and interpretations

-	PLO3 – Critical Thinking Skills in Psychology – use critical and creative thinking, skeptical inquiry, and a scientific approach to address issues related to behavior and mental processes

-	PLO4 – Application of Psychology – apply psychological principles to individual, interpersonal, group, and societal issues

-	PLO5 – Values in Psychology – value empirical evidence, tolerate ambiguity, act ethically, and recognize their role and responsibility as a member of society

Each assignment in this course maps onto one or more of these PLOs, with full coverage over all assignments in the course. PLOs 1-3 are emphasized in the first weeks of the course, and PLOs 2-5 are emphasized in the subsequent weeks of the course.

# Required Materials {#requiredmaterials}

## Canvas and E-Mail

All graded assignments will be accepted in electronic form using the Canvas learning management system assignments page (Canvas is available at https://sjsu.instructure.com/). Communication regarding the course will be posted to Canvas or sent via the e-mail address linked to your MySJSU account. It is your responsibility to make sure you are enrolled in Canvas and receiving my emails.

## Required Texts/Readings

There is no textbook required for this course. 

We will learn and practice how to derive meaning from scientific literature. Readings will emphasize primary sources and include supplemental readings. All reading assignments  will be provided on Canvas.

## Computer

A laptop or tablet computer with Internet access will be necessary to participate in class activities, take exams, and for your use outside of class. In lieu of a computer or tablet, a smartphone may be used but is unlikely to provide a good experience. You will need a keyboard and the ability to browse web sites and use spreadsheets, a calculator, a word processor, and a stopwatch. If you do not have a laptop or tablet computer available for this course, please meet with me to discuss free options for computer resources. I will work with you to find acceptable free computing resources. 

You may choose to meet with me via <a href="https://sjsu.zoom.us">Zoom</a>. A webcam and microphone are recommended but not required. For your security, I recommend that you disable or cover your webcam when not in use.

This course may require occasional use of software such as Google Docs and Sheets. I will provide instruction in the use of the software; you do not need to start the course with this knowledge. You do *not* need to purchase licenses for any software.

In case you need them, these software packages are available to you at no cost:

- [RStudio](https://www.rstudio.com)

- [R](https://cran.r-project.org)

- [SPSS](https://www.sjsu.edu/it/services/collaboration/software/instructions.php)

- [G*Power](https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower)

- [Adobe Creative Cloud](https://www.sjsu.edu/ecampus/software-tools/teaching-tools/video-creative/adobe/students.php)

- [Microsoft Office](https://www.office.com/getoffice365)

- [Google Drive](https://sjsu.drive.google.com)
 
# Grading Policy {#grading}

## Determination of Grades

Grades will be available to you on Canvas throughout the semester. Grades are assigned based on your final point total out of 1000 points for the course:

--------------------------------------
Grade                 Points
--------------------- ----------------
A plus	              > 965 points

A	                    916 to 965 points

A minus	              896 to 915 points

B plus                866 to 895 points

B	                    816 to 865 points

B minus	              796 to 815 points

C plus	              766 to 795 points

C	                    716 to 765 points

C minus	              696 to 715 points

D plus	              666 to 695 points

D	                    616 to 665 points

D minus               595 to 615 points

F	                    < 595 points
--------------------------------------

## Rounding is Included in the Grading Scale

The point totals reflect rounding up to the nearest percentage. For example, an A- would normally require 900 points (or 90% of 1000 points). With rounding, it only requires 896 points (or 89.6% of 1000 points). Because rounding is built into the grading scale, your grade will be based on your final point total, rounded to the nearest whole point (so, 895.6 points is an A-, but 895.4 points is a B+). To be fair to everyone in the class, these are firm cutoffs.

# Course Requirements and Assignments {#assignments}

## AI Policy
It is my goal to help prepare you to use AI effectively, safely, and ethically. Our course needs an AI policy to help you learn about AI while preventing it from sabotaging your learning. When I say AI or LLM in this class, I mean any and all of these: AI chatbots such as ChatGPT, Google Gemini, Claude, Meta AI; AI code generators such as GitHub Copilot, Tabnine; AI-enhanced presentation tools such as Gamma, Canva, Prezi; and AI-enhanced proofing tools such as Grammarly.

  - **AI use is not required in this class**: If AI use is suggested in any assignment, I will make an alternative method available that does not require AI. If you do not see one listed, please ask me.

  - **Disclose your AI use in assignments**: To avoid academic dishonesty, you must disclose your use of AI tools in all submitted work. This includes detailing how and why the tools were used, either as a brief note or as part of the assignment. If you do not disclose your AI use, you are representing that you were the sole author of the submitted work. 
  
  - **Observe assignment-level restrictions on AI **: Some assignment categories have limits on AI use. This is to avoid making the assignment a waste of a time. For example, if you have AI take a quiz for you, you are missing an opportunity for practice and feedback.
  
  - **Take responsibility for AI accuracy**: AI tools make mistakes. You are responsible for the accuracy of anything you generate with AI. Because of this, you should not trust anything the AI generates. This makes AI better for brainstorming ideas, suggesting topics, drafting an outline, or recommending citations. Any claims made by the AI should be verified with another source. I may reduce your grade or ignore parts of your assignments that contain AI-generated misinformation.
  
  - **Take care with  privacy and intellectual property**: Read the privacy policy for any AI tool you use, and be aware that many of them record everything you submit, associate it with your identity, and then can retain and use these data for nearly any purpose. If your computer supports it, I highly recommend running local AI models that do not send your information to the cloud, such as [gpt4all](gpt4all.io). My course materials are copyrighted and are my intellectual property. You may not upload, post, or share any of my course materials with any AI or any website.

  - I may ask to meet with you to discuss your submitted assignments before assigning the grade. Minor violations (e.g., you misused AI on an assignment, but you were honest and disclosed it) may require re-submission of the assignment, a written warning, and a late penalty. Major violations (e.g., failing to disclose AI use or repeated violations) may result in referral to the academic integrity office and academic sanctions in this course, which can include failure of the course.


## Lecture Notes (10% of grade = 100 points)

Take your own notes while watching the weekly videos. You may choose the format (typed, handwritten and scanned, etc.) of your notes, and they may be extensive or brief, whatever is most helpful to you. For full credit, submit notes covering every assigned video.  Eleven notes assignments will be worth 10 points each, and the lowest score will be dropped, for a total of 100 points. The grade may be reduced if the notes do not reflect the content of each lecture videos. Maps to CLO1-4.

AI restriction: Because this is credit for minimal rehearsal of the lecture content, you cannot use AI to summarize videos or slides for you. As long as you have authored the notes, you may use AI to ask questions or explain concepts. However, consider e-mailing me as well, because I am happy to answer your questions. See the AI policy, above.

## Weekly Reflection Assignments (40% of grade = 396 points)

A weekly reflection assignment will be available on each week’s topic on Canvas. Eleven reflection assignments will be worth 36 points each, for a total of 396 points. Each assignment will be graded satisfactory/unsatisfactory according to the rubric posted to Canvas. Unsatisfactory assignments will receive feedback and can be resubmitted during the semester without a grade penalty. Maps to CLO1-4.

AI restriction: You may not copy content written by other students or AI to write your response to reflection assignments, although you may use these tools to facilitate your learning. This is the difference between discussing and asking questions about your activity assignment, which are acceptable, and asking someone (or AI) to write your assignment for you, which is not acceptable. See the AI policy, above.

## Literature Review Paper and Presentation (20% of grade = 200 points)

You will prepare a literature review on a human-systems integration research topic. The literature review will be used for your proposal assignment. You will be asked to present your literature review in the form of a presentation and paper. Your literature review will be shared with the class and our guest speakers. You will have the option of early feedback so that you can anticipate your grade. This assignment will be assessed according to the rubric posted to Canvas. Maps to CLO2 and CLO4.

AI warning: AI may be helpful in suggesting or summarizing literature, but you are responsible for knowing the content of your literature review and its accuracy. Your video presentation must be presented in your own words and not scripted by AI. See the AI policy, above.

## Proposal Paper and Presentation (30% of grade = 300 points)

You will prepare a proposal for a novel human-systems integration study. You will be asked to present your proposal in the form of a presentation and a paper. You will have the option of early feedback so that you can anticipate your grade. This assignment will be assessed according to the rubric posted to Canvas. Maps to CLO2 and CLO4.

AI restriction: You may not copy content written by other students or AI to write your proposal paper, although you may use these tools to facilitate your learning. This is the difference between discussing and asking questions about your activity assignment, which are acceptable, and asking someone (or AI) to write your assignment for you, which is not acceptable. Your video presentation must be presented in your own words and not scripted by AI. See the AI policy, above.

## Research Engagement: Choose One (5% of grade = 54 points)

Attend the free Spartan Annual Research Conference SPARC or another conference relevant to our course this semester. Alternative conference and assignment options, such as research participation, will be announced in class. You may also suggest an alternative assignment, and I will work with you to pre-approve a relevant assignment of similar effort. This assignment is graded for completion. Maps to CLO1 and CLO3.

## Description of Capstone Requirements
As a capstone course, the following requirements will be met:

- Demonstrated Learning Requirement: Students will develop a viable, original research study.

- Competence in oral and written communication: Students will author a proposal describing their study and present their proposal in the form of an oral presentation.

- Integration of skills across the major: Students will use skills developed throughout their degree to develop an original study. The course will explicitly consider how cognitive psychology, perception, social psychology, industrial/organizational psychology and the science of learning inform human-systems integration research.

- Library use: All source materials are available in the library. Students will use the library to find additional references.

- Critical evaluation of literature and research reports will be emphasized in class and small-group discussions.

- Application of existing literature to human-systems integration is a central skill developed in the course.

- Deliverables include a paper and presentation incorporating critical evaluation of literature.


## Late Assignments and Make-Ups {#makeup}

Assignments are due as indicated on Canvas, and the deadlines are strict. Because of this, I encourage you to avoid submitting assignments in the last two hours before the due date whenever possible. Late activity assignments and reflection questions will be accepted with a 20% penalty per day. That is, an assignment submitted between 0 and 23 hours past the deadline will be accepted with a 20% reduction included after grading. An assignment submitted 24 hours past the deadline will be accepted with a 40% reduction included after grading. Please allow extra time for me to grade late-submitted assignments. If your circumstances warrant an exception to the late assignment penalty, such as due to a health emergency, complete **[this form](https://docs.google.com/forms/d/e/1FAIpQLSepJUy_f3Y2WXoCHIAHd_5hUgq3KBK6nc8mkMCvP6_vfc41Cw/viewform?usp=sf_link)** to request an exception. **When you need an exception to the late assignment penalty, I need the request form completed as soon as you are able to complete it**. Exceptions are for exceptional, unforeseen, and unavoidable circumstances.


### No assignment submission after the last day of instruction

I can only accept assignments (except the final) until 11:59pm on the last day of instruction for the semester. At that time, all unsubmitted and unsatisfactory/no credit assignments will receive zero points. Should an event prevent you from completing the course, contact me as soon as you are able to discuss our options for an incomplete. 


## Final examination or evaluation {#final}

Faculty members are required to have a culminating activity for their courses, which can include a final examination, a final research paper or project, a final creative work or performance, a final portfolio of work, or other appropriate assignment.

The culminating activity for this course will be the final proposal presentation or paper.

# Classroom Environment {#environment}

We agree to:

-	**Mutual respect**, which means that we recognize and value that we bring different skills, experiences, and qualities to our course, and we act with regard for how our behavior affects others. As much as we can, we recognize and accommodate individual constraints that impact our work. Some ways we will show mutual respect include:
    + Respecting diverse viewpoints while affirming that ableism, classism, racism, sexism, transphobia, heterosexism, and xenophobia will not be acceptable in the physical and digital spaces that make up our course. 
  
    + Respecting our and others’ intellectual property. For students, this includes not sharing or posting copyrighted class materials. For me, this includes seeking permission before publicly sharing or posting your work (unless for an educational purpose, checking for or responding to academic dishonesty, or due to legal action). Your work may be sent to turnitin.com and/or examined using analytic tools to detect academic dishonesty. However, I will not allow turnitin.com to store your work in their repository.
  
    + We understand that we have multiple obligations and limited time. Our meetings will start promptly at times convenient for both of us.
  
    + We understand that we are all doing our best as we face our own challenges. I will expect that you put in reasonable effort on your assignments. You can expect patience and help whenever you struggle with course material. And, I am always available to meet with you should life events impact your progress in the course or success in your program.

- **Academic and professional integrity**, which means that the credibility of science and education depends on us acting ethically. Ethical violations by us or our collaborators can jeopardize our research and harm our reputation as researchers. We also know that we cannot act ethically if we do not understand what that means for researchers. Therefore, it is important that research ethics are part of your learning in this class. You can expect support and guidance when you navigate and speak up on challenging ethical situations. You can also expect no tolerance of ethical or academic integrity violations that negatively affect our class or community, including cheating and plagiarism. You can expect your instructor to follow all University policies and protocols regarding the handling of suspected academic dishonesty. Penalties can include failure of the course.

-	**Unlimited support** related to the class or your professional training and development. This means that there is no limit to the number of questions you may ask, e-mails you may send, and no restriction on the hours you can spend in meetings with me. You need never apologize for asking a question or seeking support. Time is limited but support is not; if the volume of student meetings were to become unmanageable, I will make adjustments to help all students more efficiently (for example, by answering a common question to the whole class). I am always happy to help you.

-	**Incorporation of issues of social justice**. It is my goal to help prepare you to tackle the major societal challenges we face, including COVID-19 and broader issues of equity and sustainability. Success against these challenges requires equitable participation by people of diverse backgrounds and experiences. To support this goal, this course will incorporate discussion of social justice when relevant to the course and support your evaluation of how our discipline has/can/will address social justice, as well as how it has contributed to social injustice. 

# University Policies {#policies}

Per [University Policy S16-9](http://www.sjsu.edu/senate/docs/S16-9.pdf),relevant university policy concerning all courses, such as student responsibilities, academic integrity, accommodations, dropping and adding, consent for recording of class, etc. and available student services (e.g. learning assistance, counseling, and other resources) are listed on [Syllabus Information web page](https://www.sjsu.edu/curriculum/courses/syllabus-info.php). Make sure to visit this page to review and be aware of these university policies and resources.

Success in this course is based on the expectation that students will spend, for each unit of credit, a minimum of 45 hours over the length of the course (normally three hours per unit per week) for instruction, preparation/studying, or course related activities, including but not limited to internships, labs, and clinical practica. Other course structures will have equivalent workload expectations as described in the syllabus. 

## You need my permission before making any recordings in class
You must obtain the instructor’s permission to make any audio or video recordings in this class. Unless otherwise specified, course content and materials created by your instructor are copyrighted and cannot be redistributed.

# Library Liaison 
Our library liaison is Christa Bailey. Email: christa.bailey@sjsu.edu

# Additional Information
All assignments in this course should be submitted in APA format. The writing requirement is described above.

# Course Schedule {#schedule}

The course schedule is tentative and likely to change; modifications will be posted to this page.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Week Date                   Topics                                                          
---- ---------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------- 
1	    Thu., Jan. 23	        Introduction    

2	    Mon., Jan. 27         Applied research methods; Funding opportunities   

3	    Mon., Feb. 3          Sociotechnical systems and modeling; Elements of a research proposal                               
      
4	    Mon., Feb. 10         Simulation and training 
      
5	    Mon., Feb. 17         Funding sources; Publication and research ethics; Task analysis   

      Tue., Feb. 18         **Last day to drop or add**

6	    Mon., Feb. 24         Decision making among cybersecurity professionals; Finding and reading literature

7	    Mon., Mar. 3          Medical product design; Citing literature; Patient safety                         

8	    Mon., Mar. 10         HSI in Medicine: Error, teamwork, and digital health; Summarizing literature and identifying research needs (speaker)
                  
9	    Mon., Mar. 17         Human-automation interaction in transportation

10	  Mon., Mar. 24         Human performance: Workload, motion sickness, fatigue, sustained attention

11	  Mon., Mar. 31         **Spring Recess**                                                    

12	  Mon., Apr. 7          Literature review presentations

13	  Mon., Apr. 14         Airspace coordination; Planning a study

14	  Mon., Apr. 21         Cyberspace as a system: Cyber workforce, threats, automation and orchestration; scientific merit, societal impact, and implications for practice     

15	  Mon., Apr. 28         Cybersecurity in daily life: Cyber hygiene, privacy, usability, trust; Assembling your proposal    

16	  Mon., May 5           Proposal workshop  

      Mon., May 12          Last day of instruction, assignment submission ends 11:59 pm

Final Fri., May 16	        Proposal presentations due 5:30 pm
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



